spring:
  application:
    name: muse-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/musemaker
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
